# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

activity_controllers:
    resource: ../src/Activity/Application/Controller/
    type: attribute

ai_controllers:
    resource: ../src/AI/Application/Controller/
    type: attribute

cart_controllers:
    resource: ../src/Cart/Application/Controller/
    type: attribute

catalog_controllers:
    resource: ../src/Catalog/Application/Controller/
    type: attribute

debug_controllers:
    resource: ../src/Debug/Application/Controller/
    type: attribute

inventory_controllers:
    resource: ../src/Inventory/Application/Controller/
    type: attribute

picnic_controllers:
    resource: ../src/Picnic/Application/Controller/
    type: attribute

printer_controllers:
    resource: ../src/Printer/Application/Controller/
    type: attribute

scanner_controllers:
    resource: ../src/Scanner/Application/Controller/
    type: attribute
