[program:scanner-listen]
command=php /var/www/html/bin/console scanner:listen
directory=/var/www/html
autostart=true
autorestart=unexpected
startretries=99
user=root
priority=40
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
